services:
  redis:
    image: redis:latest
    ports:
      - 6379:6379
    command: ['redis-server', '--appendonly', 'yes']
    volumes:
      - redis-data:/data

  redis-commander:
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:6379
      - HTTP_USER=root
      - HTTP_PASSWORD=secret
    ports:
      - 8081:8081
    depends_on:
      - redis

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: appuser
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  frontend:
    build: ./
    ports:
      - 5000:5000
    environment:
      ASPNETCORE_URLS: http://+:5000
      ConnectionStrings__DefaultConnection: Server=db; Port=5432; User id=appuser; Password=secret; Database=999scraper
      ConnectionStrings__Redis: redis
      Token__Key: Super ultra secure key for Testing123
      Token__audience: ClientApp
      Token__Issuer: AndiQ
    depends_on:
      - redis-commander
      - db
      - adminer

volumes:
  redis-data:
